{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "matrix-media-repo.serviceAccountName" . }}
  labels:
{{ include "matrix-media-repo.labels" . | indent 4 }}
{{- end -}}
